/* Copyright (c) 2024 ForeFront, Inc. All Rights Reserved. Subject to ForeFront, Inc. licensing. */
export const labels = {
    monthJanuary: "January",
    monthFebruary: "February",
    monthMarch: "March",
    monthApril: "April",
    monthMay: "May",
    monthJune: "June",
    monthJuly: "July",
    monthAugust: "August",
    monthSeptember: "September",
    monthOctober: "October",
    monthNovember: "November",
    monthDecember: "December",
    weekdayShortMon: "Mon",
    weekdayShortTue: "Tue",
    weekdayShortWed: "Wed",
    weekdayShortThu: "Thu",
    weekdayShortFri: "Fri",
    weekdayShortSat: "Sat",
    weekdayShortSun: "Sun",
    weekdayMonday: "Monday",
    weekdayTuesday: "Tuesday",
    weekdayWednesday: "Wednesday",
    weekdayThursday: "Thursday",
    weekdayFriday: "Friday",
    weekdaySaturday: "Saturday",
    weekdaySunday: "Sunday",
    todayLink: "Today",
    errorMessage: "Date {0} is invalid. Pick another date.",
}